### ISSUE TITLE
Missing assets for the latest release

### ISSUE THREAD

**Issue by orhun** [nabijaczleweli/termimage#20]
Latest release ([v1.2.0](https://github.com/nabijaczleweli/termimage/releases/tag/v1.2.0)) does not contain the following assets although the previous releases had them:

- `termimage-doc-v1.2.0.tbz2 `
- `termimage-man-v1.2.0.tbz2`
- `termimage-v1.2.0`

**Comment by nabijaczleweli** [comment]
Yes, they're generated by travis and travis died. I build binary releases on https://debian.nabijaczleweli.xyz, and have little interest in re-inventing the CI infra for this. I would happily upload the Debian binaries manually to the tag, but, even after close to a decade, it's impossible to Just do that on github since I'd have to break the "release" that was created from the tag by appveyor. In many ways this is why I'm a [shart](https://sr.ht/~nabijaczleweli/) user now.

**Comment by orhun** [comment]
Interesting, so there isn't a way to get pre-built binaries for `termimage` now? Asking because I am maintaining [`termimage-bin`](https://aur.archlinux.org/packages/termimage-bin) AUR package and it would make sense to note this on the package page.

**Comment by nabijaczleweli** [comment]
Not from the releases github "releases" page. Instead you can do:
```
curl -SOL https://debian.nabijaczleweli.xyz/pool/main/t/termimage/termimage_${VER}-1_amd64.deb
ar x termimage_${VER}-1_amd64.deb data.tar.xz
tar -xaf data.tar.xz ./usr/bin/termimage
```
to that same effect (I build these from https://github.com/nabijaczleweli/termimage.deb instead of CI, see debian/patches and debian/rules there – the manual and fish/bash completion are in data.tar.xz as well, so you really ought to be able to do a no-build (re)package).

You can do signature verification, even!
```
$ curl -SOL https://debian.nabijaczleweli.xyz/changes/termimage_1.2.1-1_amd64.changes
$ grep -F termimage_1.2.1-1_amd64.deb termimage_1.2.1-1_amd64.changes
 d927b66a30b03a78eeefb283ea712f37be00f0b6 830532 termimage_1.2.1-1_amd64.deb
 5400eb24501c8e9b6a61f254ac13f7b1c9c93ae818386a6eb35cb4d7b16a7e38 830532 termimage_1.2.1-1_amd64.deb
 e75d13e3c949a27bbdf7cdc609132eb6 830532 graphics optional termimage_1.2.1-1_amd64.deb
$ sha256sum termimage_1.2.1-1_amd64.deb
5400eb24501c8e9b6a61f254ac13f7b1c9c93ae818386a6eb35cb4d7b16a7e38  termimage_1.2.1-1_amd64.deb

$ gpg --verify < termimage_1.2.1-1_amd64.changes
gpg: Signature made Sat 15 Jul 2023 19:18:20 CEST
gpg:                using RSA key 7D69474E84028C5CC0C44163BCFD0B018D2658F1
gpg:                issuer "nabijaczleweli@nabijaczleweli.xyz"
gpg: Good signature from "наб <nabijaczleweli@nabijaczleweli.xyz>" [ultimate]
gpg:                 aka "наб <nabijaczleweli@gmail.com>" [ultimate]
gpg:                 aka "nabijaczleweli <nabijaczleweli@gmail.com>" [ultimate]
```

**Comment by orhun** [comment]
Thank you, the AUR package is updated!
